### ISSUE TITLE
FODESystem not defined. FractionalDiffEq v0.3.5 

### ISSUE THREAD

**Issue by Raul-Barajas** [SciFracX/FractionalDiffEq.jl#106]
When you try running the following example:

using FractionalDiffEq, Plots
function chua!(du, x, p, t)
    a, b, c, m0, m1 = p
    du[1] = a*(x[2]-x[1]-(m1*x[1]+0.5*(m0-m1)*(abs(x[1]+1)-abs(x[1]-1))))
    du[2] = x[1]-x[2]+x[3]
    du[3] = -b*x[2]-c*x[3]
end
α = [0.93, 0.99, 0.92];
x0 = [0.2; -0.1; 0.1];
tspan = (0, 100);
p = [10.725, 10.593, 0.268, -1.1726, -0.7872]
prob = FODESystem(chua!, α, x0, tspan, p)
sol = solve(prob, NonLinearAlg(), dt=0.01)
plot(sol, vars=(1, 2), title="Chua System", legend=:bottomright)

You get the following error:
ERROR: UndefVarError: `FODESystem` not defined

This did not happen in version 0.3.1. Is there a different syntax for version 0.3.5? Can you help me? 

Thank you very much.

**Comment by ErikQQY** [comment]
The documentations didn’t update in time, as for FODE, the problem constructor should be the same as FODEProblem.

**Comment by ErikQQY** [comment]
The new updated README has the correct usage now.
