### ISSUE TITLE
UndefVarError: FODESystem not defined

### ISSUE THREAD

**Issue by moeinkh88** [SciFracX/FractionalDiffEq.jl#34]
Hi, I am trying to run some examples based on the instruction in your documents. But, the solvers are not defined! For example, FODESystem and SingleTermFODEProblem can't be recognized from the package. 
I would like to benchmark (speed and accuracy) some of your solvers that are compatible with our package: [FdeSolver.jl](https://github.com/JuliaTurkuDataScience/FdeSolver.jl).

**Comment by moeinkh88** [comment]
I clone the package to test it in a local environment. But, there are some sub-packages, like SpecialMatrices, needed to be imported. I recommend importing the required packages into the module.

**Comment by moeinkh88** [comment]
From examples: abelinteqexample.j
Line 9: plot(tspan, sol, title="Second kind Abel integral equation", label="Numerical")

Error
> Cannot convert FIESolution to series data for plotting
in eval at [base/boot.jl:360](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#) 
in top-level scope at [abelinteqexample.jl:9](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in  at [Plots/cc8wh/src/plot.jl:51](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in var"#plot#133" at [Plots/cc8wh/src/plot.jl:57](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in _plot! at [Plots/cc8wh/src/plot.jl:178](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in _process_userrecipes at [Plots/cc8wh/src/pipeline.jl:85](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in apply_recipe at [RecipesBase/G4s6f/src/RecipesBase.jl:279](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in macro expansion at [Plots/cc8wh/src/series.jl:129](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#) 
in convertToAnyVector at [Plots/cc8wh/src/series.jl:29](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in prepareSeriesData at [Plots/cc8wh/src/series.jl:14](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in error at [base/error.jl:33](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)

**Comment by moeinkh88** [comment]
BTW, have you tried dispatch methods? https://docs.julialang.org/en/v1/manual/metaprogramming/#Macros-and-dispatch

**Comment by moeinkh88** [comment]
examples: chua.jl
line 16: result = solve(prob, h, NonLinearAlg())

> BoundsError
in eval at [base/boot.jl:360](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#) 
in top-level scope at [chua.jl:16](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in solve at [SciFracX/FractionalDiffEq.jl/src/fodesystem/NonLinear.jl:15](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in solve at [SciFracX/FractionalDiffEq.jl/src/fodesystem/NonLinear.jl:16](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in getindex at [base/number.jl:96](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)

**Comment by ErikQQY** [comment]
Thanks for the quick feedback!!
Very sorry for the error, as for the fractional integral equations, we can use ```SpectralUltraspherical``` method to solve the FIEProblem, I has recently add the recipe for solution visualization, so to solve fractional integral equations, for example

$$
I^{0.5}u(x)+u(x)=1
$$

```julia
using FractionalDiffEq, Plots, SpecialFunctions
analytical(x)=exp(1+x)*erfc(sqrt(1+x))
tspan = LinRange(-1, 1, 100)
prob = FIEProblem([1, 1], [0, 0.5], 1, tspan)
sol = solve(prob, 20, SpectralUltraspherical())
solanalytical = analytical.(tspan)
plot(sol, title="Second kind Abel integral equation", label="Numerical")
plot!(tspan, solanalytical, ls=:dash, label="Analytical")
```

**Comment by ErikQQY** [comment]
> BTW, have you tried dispatch methods? https://docs.julialang.org/en/v1/manual/metaprogramming/#Macros-and-dispatch

Sure!😄

There are many dispatched methods for the ease of usage, see ```GL``` method for both ```SingleTermFODEProblem``` and ```FODESystem```

**Comment by ErikQQY** [comment]
> OK nice! As you have already a good collection of solving methods, did you benchmark your developed methods?

I am still working on this, yesterday I just benchmarked the solvers for ```MultiTermsFODEProblem```:

```julia
using FractionalDiffEq, Plots, LinearAlgebra

h = 1e-2; tspan = (0, 30)
rightfun(x, y) = 172/125*cos(4/5*x)
multitermprob = MultiTermsFODEProblem([1, 1/16, 4/5, 3/2, 1/25, 6/5], [3, 2.5, 2, 1, 0.5, 0], rightfun, [1, 4/5, -16/25, 0, 0, 0], tspan)

realfun(x)=sqrt(2)*sin(4*x/5+π/4)
sol1 = solve(multitermprob, h, PIEX())
sol2 = solve(multitermprob, h, PIIMRect())
sol3 = solve(multitermprob, h, PIIMTrap())
sol4 = solve(multitermprob, h, PIPECE())

realsol = realfun.(collect(0:h:30))
err1 = norm(sol1.u-realsol)
err2 = norm(sol2.u-realsol)
err3 = norm(sol3.u-realsol)
err4 = norm(sol4.u-realsol)
```

**Comment by moeinkh88** [comment]
> > OK nice! As you have already a good collection of solving methods, did you benchmark your developed methods?
> 
> I am still working on this, yesterday I just benchmarked the solvers for `MultiTermsFODEProblem`:
> 
> ```julia
> using FractionalDiffEq, Plots, LinearAlgebra
> 
> h = 1e-2; tspan = (0, 30)
> rightfun(x, y) = 172/125*cos(4/5*x)
> multitermprob = MultiTermsFODEProblem([1, 1/16, 4/5, 3/2, 1/25, 6/5], [3, 2.5, 2, 1, 0.5, 0], rightfun, [1, 4/5, -16/25, 0, 0, 0], tspan)
> 
> realfun(x)=sqrt(2)*sin(4*x/5+π/4)
> sol1 = solve(multitermprob, h, PIEX())
> sol2 = solve(multitermprob, h, PIIMRect())
> sol3 = solve(multitermprob, h, PIIMTrap())
> sol4 = solve(multitermprob, h, PIPECE())
> 
> realsol = realfun.(collect(0:h:30))
> err1 = norm(sol1.u-realsol)
> err2 = norm(sol2.u-realsol)
> err3 = norm(sol3.u-realsol)
> err4 = norm(sol4.u-realsol)
> ```

Nice, I will check some as well if I can.

**Comment by ErikQQY** [comment]
Benchmarks for other solvers are not ready yet, but I think that should be a 

> > > BTW, have you tried dispatch methods? https://docs.julialang.org/en/v1/manual/metaprogramming/#Macros-and-dispatch
> > 
> > 
> > Sure!smile
> > There are many dispatched methods for the ease of usage, see `GL` method for both `SingleTermFODEProblem` and `FODESystem`
> 
> It would be nicer if you can have dispatched based on the problem so that the user no need to determine the method. Do you have something like this? It makes the package more practical for those who are not familiar with mathematics or the methods.

Of course, I think this would also be nicer and easier for users so they don't have to worry about choosing methods, I will add this in the near future. Thanks for your valuable feedback!!!😄

**Comment by moeinkh88** [comment]
I have tried to debug the example using PECE, but it takes time. 

In folder example: example.jl
line 9: sol = solve(prob, 0.01, PECE())

Error:
> UndefVarError: LayoutPointers not defined
in eval at [base/boot.jl:360](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#) 
in top-level scope at [example.jl:9](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in solve at [SciFracX/FractionalDiffEq.jl/src/singletermfode/PECE.jl:245](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in macro expansion at [base/simdloop.jl:77](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#) 
in macro expansion at [SciFracX/FractionalDiffEq.jl/src/singletermfode/PECE.jl:251](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#) 
in predictor at [SciFracX/FractionalDiffEq.jl/src/singletermfode/PECE.jl:279](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)
in _turbo_! at [LoopVectorization/5UaTq/src/reconstruct_loopset.jl:704](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#) 
in macro expansion at [LoopVectorization/5UaTq/src/reconstruct_loopset.jl:704](https://github.com/SciFracX/FractionalDiffEq.jl/issues/34#)

**Comment by ErikQQY** [comment]
That's weird, I have never encountered that problem before and it works fine on my computer, also I think that error is something with ```@simd``` macro.🤔

**Comment by ErikQQY** [comment]
![example](https://user-images.githubusercontent.com/52615090/171402925-3cc9723f-7b15-40dd-99e9-3ca71afd7c57.png)
