### ISSUE TITLE
NonLinearAlg in julia

### ISSUE THREAD

**Issue by beloved321** [SciFracX/FractionalDiffEq.jl#35]
julia> result = solve(prob, h, tf, NonLinearAlg(1))
ERROR: MethodError: no method matching NonLinearAlg(::Int64)
can some one put me through this

**Comment by ErikQQY** [comment]
Hi there!!
I think the right usage should be:

```julia
solve(prob, h, NonLinearAlg())
```

**Comment by ErikQQY** [comment]
I am doing a lot of refactoring recently, so the documents might be a little outdated, I just released version 0.2.6, and I think this version will improve the experience a lot.😄
