### ISSUE TITLE
suggestions for mutliterm problems

### ISSUE THREAD

**Issue by moeinkh88** [SciFracX/FractionalDiffEq.jl#38]
Hi,

For multiterm examples, like bagleytorvik, I have found that we need to use arguments as parameters of the problem.
But, isn't it better to have a solver function for a class of problems with muliterm of derivatives and let the user define the problem function manually? Like fractional ODE problems that you made, the user can define the problem and then use the function as an argument (like chua.jl). This way is more user-friendly and more flexible than having a specific problem inside the solver and giving control of the parameters to the user.

**Comment by ErikQQY** [comment]
Hi there, I am not sure if I get what you mean, for multi-terms FODE, there is `MultiTermsFODEProblem` we can use to define our problems:

https://github.com/SciFracX/FractionalDiffEq.jl#a-sophisticated-example

Do we need to do something else?

**Comment by moeinkh88** [comment]
OK
So, can we solve the Bagelytorvik equation by using MultiTermsFODEProblem? If so, why is there another separate solver specifically for Bagelytorvik?

**Comment by ErikQQY** [comment]
Yeah, `MultiTermsFODEProblem` can solve BagleyTorvik equations, that solver was initially designed to test the solvers, and I think now that function can be removed.
