### ISSUE TITLE
Solution objects for FODESystem, etc. ?

### ISSUE THREAD

**Issue by jClugstor** [SciFracX/FractionalDiffEq.jl#44]
I noticed that when solving FODESystem it doesn't return a FDESolution object, but when solving a single term project it does use a solution object. 

Is there a particular reason for this, and what would be needed to have every type of FDE problem return an object solution?

**Comment by ErikQQY** [comment]
Sorry for the late response, I have been a bit busy lately🤦‍♂️

For now, every solution type such as ```FODESolution``` has a plot recipe to make convenient visualization. I have not implemented the solution type for ```FODESystemSolution```.

I think to make a ```FODESystemSolution```, we can implement it like this:

```julia
struct FODESystemSolution <: AbstractFDESolution
t::AbstractArray
u::AbstractArray
end
```

But as for the visualization recipe, I have not investigated it yet.

**Comment by jClugstor** [comment]
Looking at SciML, it look like by default they use the interpolated function and plot evenly spaced points. If the option to interpolate is off it looks like they just plot every point from the solver. It looks like you can tell it which variables to plot using a vector of tuples: https://diffeq.sciml.ai/stable/basics/plot/. I can't seem to find the source code for the plot recipes, but I'm sure it's somewhere. Also, I think if the SciML interface was followed (http://devdocs.sciml.ai/latest/contributing/defining_problems/) it could take care of the plotting and the interpolation.
