### ISSUE TITLE
Package not running

### ISSUE THREAD

**Issue by masteling** [SciFracX/FractionalDiffEq.jl#55]
I have been using this package for a couple of months. And for the last few weeks I keep getting this error:

![image](https://user-images.githubusercontent.com/24229030/186923983-fdeeeb64-fbeb-496f-8c94-8aef464c4c38.png)

These are the only packages in my installation:
![image](https://user-images.githubusercontent.com/24229030/186924294-45581ce0-2ce1-4ea4-8c02-d98d185b6e8d.png)

I tried adding LinearAlgebra to my installation but that did not change the error.

Thank you for your help,
Mariana

**Comment by ErikQQY** [comment]
Sorry for the problems! I noticed the version of FractionalDiffEq.jl on your computer is 0.2.0, I think maybe you should upgrade to the latest version 0.2.10, then I think the problems would be gone.

**Comment by masteling** [comment]
When I try to install 0.2.10 I get this:

![image](https://user-images.githubusercontent.com/24229030/186963758-81221b93-da45-46bc-a178-fde7cc87bd2e.png)

I need to use both fracdiff (from FractionalCalculus) and MultiTermsFODEProblem (from FractionalDiffEq) in the same for loop.

Do you have suggestions on how I can do that? Right now I can either do one or the other, as when I have both packages I get this error.

**Comment by ErikQQY** [comment]
Sorry for the compat problems, I just released version 0.2.11, with a higher compat for SpecialFunctions.jl, I think this would solve the problem😄

**Comment by masteling** [comment]
Thank you for releasing the new version. It solved the issues I was having.
