### ISSUE TITLE
Cannot `convert` an object of type 

### ISSUE THREAD

**Issue by ksw8755** [SciFracX/FractionalDiffEq.jl#57]
Since last Friday, it has shown, Cannot `convert` an object of type and has not worked it. Could you help me how to fix it?

MethodError: Cannot `convert` an object of type 
  Tuple{Int64, Int64} to an object of type 
  AbstractArray
Closest candidates are:
  convert(::Type{T}, ::LinearAlgebra.Factorization) where T<:AbstractArray at C:\Users\skim\AppData\Local\Programs\Julia-1.8.2\share\julia\stdlib\v1.8\LinearAlgebra\src\factorization.jl:58
  convert(::Type{T}, ::Intervals.IntervalSet) where T<:AbstractArray at C:\Users\skim\.julia\packages\Intervals\wE73a\src\interval_sets.jl:64
  convert(::Type{T}, ::Intervals.AnchoredInterval{P, T}) where {P, T} at C:\Users\skim\.julia\packages\Intervals\wE73a\src\anchoredinterval.jl:181
  ...

Stacktrace:
 [1] convert(#unused#::Type{Union{Nothing, AbstractArray}}, x::Tuple{Int64, Int64})
   @ Base .\some.jl:36
 [2] MultiTermsFODEProblem(parameters::Vector{Float64}, orders::Vector{Float64}, rightfun::Function, rparameters::Vector{Int64}, rorders::Tuple{Int64, Int64})
   @ FractionalDiffEq C:\Users\skim\.julia\packages\FractionalDiffEq\uk4Ug\src\PECE.jl:19
 [3] top-level scope
   @ In[4]:4
 [4] eval
   @ .\boot.jl:368 [inlined]
 [5] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1428

**Comment by ErikQQY** [comment]
Hi there! Sorry for the late response! Could you tell me the testing example?

I see that you are using algorithms for ``MultiTermsFODEProblem``. Could you tell me the testing example?

**Comment by ksw8755** [comment]
Dear Qingyu Qu,

Thank you for getting back to me. I waited for a long time, and now I have
deleted the package. But I will install the package again and let you know
if the same problem occurs again.

I appreciate your consideration.

Sincerely,
Seonguk Kim.

2023년 1월 4일 (수) 오전 12:34, Qingyu Qu ***@***.***>님이 작성:
