### ISSUE TITLE
FODEMatrixDiscrete algorithm not working with some functions

### ISSUE THREAD

**Issue by khaledharizb** [SciFracX/FractionalDiffEq.jl#78]
I would like to solve the following problem where the righfunc is given by 8 if x<= 0 and 0 otherwise. However, with FODEMatrixDiscrete() algorithm does not work

```
h=0.075
f(x) =  (x <= 1) ? 8 : 0;
prob = MultiTermsFODEProblem([1, 1 , 1], [2, 3/2 , 0],  f , [0, 0], (0, 30))
sol = solve(prob, h, FODEMatrixDiscrete())
```

This example from [     http://www.mathworks.com/matlabcentral/fileexchange/22071](url) where the same algorithm is used by Matlab.

**Comment by ErikQQY** [comment]
Solved in #54
