### ISSUE TITLE
example folder issues

### ISSUE THREAD

**Issue by Khurramcoder** [SciFracX/FractionalDiffEq.jl#79]
I'm facing following list of issues in example folder
1; chua_short_memory.jl              tn not define
2:Bagleytorvik.jl                             Bagleytorvik.  not define
3;Brusselator.jl                     not evaluating
4 classical.jl              FODESystem no method  matching
5; complicated_example.jl                PIIMRect not define
6; delay_Pi_example.jl                   DelayPI not define
7;delaychen.jl             invalid redefinition of constant psi
8diffusion.jl            FPDEMatrixDiscrete not define
9;example.jl      ERROR: MethodError: no method matching fun(::Float64, ::Nothing,::Float64)
10;fdde_matrix.jl   ERROR: invalid redefinition of constant f
11;

**Comment by Khurramcoder** [comment]
Please check example folder half of examples have errors

**Comment by ErikQQY** [comment]
Sorry for the late response and the errors, FractionalDiffEq.jl is undergoing a major overhaul, some examples and docs are not updated timely, the new PR should fix all the errors.
